# config/deploy.yml

service: redmine
image: joungsik/redmine

servers:
  web:
    hosts:
      - <%= ENV.fetch("SSH_HOST") %>
    proxy: false

env:

registry:
  server: ghcr.io
  username: <%= ENV.fetch("REGISTRY_USER") %>
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

volumes:
  - /home/joungsik/redmine/data:/data
  - /home/joungsik/redmine/storage:/storage
  - /home/joungsik/redmine/plugins:/rails/plugins
  - /home/joungsik/redmine/repositories:/gitrepo

builder:
  arch: amd64

ssh:
  user: <%= ENV.fetch("SSH_USER") %>
