# config/deploy.yml

service: redmine
image: joungsik/redmine

servers:
  web:
    hosts:
      - <%= ENV.fetch("SSH_HOST") %>

registry:
  server: ghcr.io
  username: <%= ENV.fetch("REGISTRY_USER") %>
  password:
    - KAMAL_REGISTRY_PASSWORD

env:
  secret:
    - RAILS_MASTER_KEY

volumes:
  - /home/joungsik/workspace/redmine_data:/data
  - /home/joungsik/workspace/redmine_plugins:/rails/plugins

proxy:
  ssl: true
  host: redmine.joungsik.com

builder:
  arch: amd64

ssh:
  user: <%= ENV.fetch("SSH_USER") %>
