name: Tests

on:
  push:

jobs:
  tests:
    name: test ${{matrix.db}} ruby-${{ matrix.ruby }}
    runs-on: ubuntu-latest

    strategy:
      matrix:
        ruby: [ '3.4' ]
        db: [ 'sqlite3' ]
      fail-fast: false

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Redmine test environment
        uses: ./.github/actions/setup-redmine
        with:
          db-type: ${{ matrix.db }}
          ruby-version: ${{ matrix.ruby }}

      - name: Run tests
        run: |
          bin/rails test

      - name: Run bazaar non ascii test
        env:
          LANG: en_US.ISO8859-1
          LC_ALL: en_US.ISO8859-1
        run: |
          bin/rails test test/unit/repository_bazaar_test.rb

      - name: Run autoload test
        run: |
          bin/rails test:autoload

  system-tests:
    name: system test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Redmine test environment
        uses: ./.github/actions/setup-redmine
        with:
          db-type: sqlite3
          ruby-version: '3.4'

      # System tests use Chrome and ChromeDriver installed on the GitHub Actions Ubuntu image.
      # They are generally updated to the latest stable versions.
      - name: Display Chrome version
        run: google-chrome --version

      - name: Run system tests
        run: bin/rails test:system
        env:
          GOOGLE_CHROME_OPTS_ARGS: headless,disable-gpu,no-sandbox,disable-dev-shm-usage

      - name: Upload system test screenshots
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: system-test-screenshots
          path: tmp/screenshots
          if-no-files-found: ignore
